version: '3'
services:

  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./my_dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
