# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_text', models.TextField(verbose_name='Текст')),
                ('article_datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('article_likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('article_dislikes', models.IntegerField(default=0, verbose_name='Количество дизлайков')),
                ('article_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.CharField(max_length=200, verbose_name='Текст')),
                ('comments_likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('comments_dislikes', models.IntegerField(default=0, verbose_name='Количество дизлайков')),
                ('comments_datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('comments_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
