# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_date',
        ),
        migrations.AddField(
            model_name='article',
            name='article_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
