# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161004_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 12, 2, 56, 237763, tzinfo=utc), verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_dislikes',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_dislikes',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
    ]
