# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20161004_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_datetime',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_datetime',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
